### ISSUE TITLE
Incorporate PostgreSQL adapter

### ISSUE THREAD

**Issue by trevordixon** [jroweboy/oxidize#1]

**Comment by trevordixon** [comment]
Blocks https://github.com/jroweboy/oxidize/issues/3 and https://github.com/jroweboy/oxidize/issues/4

**Comment by jroweboy** [comment]
We have decided that its best to not tie into any one particular database adapter at the moment and for now, we will leave any database related code in userland.

This means that adding an adapter into the main codebase is no longer relevant and as such I will close this issue.
