### ISSUE TITLE
Refactor to use closures instead of static functions

### ISSUE THREAD

**Issue by trevordixon** [jroweboy/oxidize#14]

**Comment by LeviSchuck** [comment]
Why?

**Comment by trevordixon** [comment]
Middleware.

**Comment by LeviSchuck** [comment]
You often do not do anything that requires closures when it comes to pushing on the middleware stack.

**Comment by LeviSchuck** [comment]
A misunderstanding of terminology between languages. Carry on.

**Comment by jroweboy** [comment]
Changed entirely so this is not relevant anymore.
