### ISSUE TITLE
Make Micro-Blogging example

### ISSUE THREAD

**Issue by trevordixon** [jroweboy/oxidize#20]

**Comment by LeviSchuck** [comment]
Let's make sure that our examples do not clobber with potential future cases, like "Twitter API example" as the two do not share anything except the foundational concept.

**Comment by jroweboy** [comment]
I'm probably going to end up not making this example (maybe) I have a different example in mind that I want to make as a first "actual project" in oxidize. Then I will revisit these suggestions to see if they will be worthwhile to keep around.
